### ISSUE TITLE
Is there a way to render the entire schema collapsed?

### ISSUE THREAD

**Issue by gfiore88** [amgadfahmi/angular-bubbletree#4]
Hi,
I have a question for you!

Is there a way to start with a bubbletree scheme entirely collapsed so I can choose, in a second time, which node to expand?

I think this feature could be very useful handling huge data because the bubbletree graphs become veeeery difficult to read at a first peek!

Thanks in advance!

**Comment by amgadfahmi** [comment]
@gfiore88 will look into this once am back from vacation

**Comment by amgadfahmi** [comment]
@gfiore88 let me get this clear, the tree usually doesn't load until you call the `bind` function which will start drawing the nodes and the child ones like any other type of charts. So do you want to bind only one node like on click!
If so you still need to load the parent nodes first to show them and then expose an event for the click for each node which give you the ability to alter the data source and rebind the tree again. 

Let me know your thoughts
